# bootstrap_stats.R
#
# Diversity statistics and plotting for bootstrap databases


# Internal diversity functions -------------------------------------------

.shannon_h <- function(counts) {

  counts <- counts[counts > 0]

  if (length(counts) == 0L) {
    return(NA_real_)
  }

  p <- counts / sum(counts)

  -sum(p * log(p))
}


.simpson_dominance <- function(counts) {

  counts <- counts[counts > 0]

  if (length(counts) == 0L) {
    return(NA_real_)
  }

  p <- counts / sum(counts)

  sum(p^2)
}


.gini_simpson <- function(counts) {

  d <- .simpson_dominance(counts)

  if (is.na(d)) {
    return(NA_real_)
  }

  1 - d
}


.inverse_simpson <- function(counts) {

  d <- .simpson_dominance(counts)

  if (is.na(d) || d == 0) {
    return(NA_real_)
  }

  1 / d
}


.pielou_evenness <- function(counts) {

  counts <- counts[counts > 0]

  s <- length(counts)

  if (s <= 1L) {
    return(NA_real_)
  }

  h <- .shannon_h(counts)

  h / log(s)
}


# Internal validation ----------------------------------------------------

.validate_bootstrap_stats_input <- function(boot) {

  if (!is.list(boot)) {
    stop(
      "boot must be the result returned by bootstrap_db().",
      call. = FALSE
    )
  }

  if (
    is.null(boot$composite_taxids) ||
    !is.character(boot$composite_taxids) ||
    length(boot$composite_taxids) != 1L
  ) {
    stop(
      "No composite taxid file found in the bootstrap result.\n",
      "Run bootstrap_db() with outputs including \"composite\".",
      call. = FALSE
    )
  }

  if (!file.exists(boot$composite_taxids)) {
    stop(
      "Composite taxid file does not exist: ",
      boot$composite_taxids,
      call. = FALSE
    )
  }

  if (
    is.null(boot$label_safe) ||
    is.null(boot$outdir)
  ) {
    stop(
      "boot does not appear to be a valid bootstrap_db() result.",
      call. = FALSE
    )
  }

  invisible(TRUE)
}


.read_bootstrap_taxids <- function(path) {

  tax_mat <- readr::read_tsv(
    path,
    show_col_types = FALSE,
    progress = FALSE
  )

  if (ncol(tax_mat) == 0L) {
    stop(
      "Composite taxid file contains no bootstrap columns.",
      call. = FALSE
    )
  }

  tax_mat
}


# Internal metric calculation --------------------------------------------

.compute_bootstrap_stats <- function(tax_mat) {

  sample_ids <- names(tax_mat)

  rows <- lapply(
    seq_along(sample_ids),
    function(i) {

      sample_id <- sample_ids[i]

      taxids <- tax_mat[[i]]

      taxid_text <- stringr::str_trim(
        as.character(taxids)
      )

      keep <- !is.na(taxids) &
        !is.na(taxid_text) &
        taxid_text != ""

      taxids <- taxids[keep]

      counts <- as.numeric(
        table(taxids)
      )

      db_index <- stringr::str_match(
        sample_id,
        "_db([0-9]+)$"
      )[, 2]

      db_index <- suppressWarnings(
        as.integer(db_index)
      )

      if (is.na(db_index)) {
        db_index <- i
      }

      tibble::tibble(
        sample_id = sample_id,
        replicate = db_index,
        n_draws = length(taxids),
        n_unique_taxa = length(counts),
        shannon = .shannon_h(counts),
        simpson_dominance = .simpson_dominance(counts),
        gini_simpson = .gini_simpson(counts),
        inverse_simpson = .inverse_simpson(counts),
        pielou_evenness = .pielou_evenness(counts)
      )
    }
  )

  dplyr::bind_rows(rows) |>
    dplyr::arrange(replicate)
}


#' Calculate diversity statistics for bootstrap databases
#'
#' Calculates taxid-based diversity statistics for bootstrap replicates
#' generated by [bootstrap_db()].
#'
#' Statistics are calculated from the full bootstrap draws, including
#' repeated assemblies. Assemblies sharing the same taxonomy ID therefore
#' contribute to the abundance of the same taxon.
#'
#' @param boot A bootstrap result returned by [bootstrap_db()]. The
#'   bootstrap must have been generated with `"composite"` included in
#'   `outputs`.
#' @param outdir Optional directory for the summary table. Defaults to a
#'   `metrics` directory inside the bootstrap output directory.
#' @param write Logical; write the summary table to disk. Defaults to
#'   `TRUE`.
#' @param verbose Logical; print a summary message.
#'
#' @return A list containing the diversity summary table and, when
#'   `write = TRUE`, the output path.
#'
#' @details
#' The following statistics are reported for each bootstrap replicate:
#'
#' * `n_draws`: total number of sampled assemblies.
#' * `n_unique_taxa`: number of unique taxonomy IDs.
#' * `shannon`: Shannon diversity index.
#' * `simpson_dominance`: Simpson dominance index.
#' * `gini_simpson`: Gini-Simpson diversity index.
#' * `inverse_simpson`: inverse Simpson diversity.
#' * `pielou_evenness`: Pielou's evenness.
#'
#' @examples
#' \dontrun{
#' boot <- bootstrap_db(
#'   db,
#'   n_boot = 100,
#'   label = "rickettsia",
#'   seed = 42
#' )
#'
#' stats <- bootstrap_stats(boot)
#'
#' stats$summary
#' }
#'
#' @export
bootstrap_stats <- function(
    boot,
    outdir = NULL,
    write = TRUE,
    verbose = TRUE
) {

  .validate_bootstrap_stats_input(boot)

  tax_mat <- .read_bootstrap_taxids(
    boot$composite_taxids
  )

  summary_tbl <- .compute_bootstrap_stats(
    tax_mat
  )

  out_path <- NULL

  if (isTRUE(write)) {

    if (is.null(outdir)) {
      outdir <- file.path(
        boot$outdir,
        "metrics"
      )
    }

    if (
      !is.character(outdir) ||
      length(outdir) != 1L ||
      is.na(outdir) ||
      stringr::str_trim(outdir) == ""
    ) {
      stop(
        "outdir must be a single non-empty path.",
        call. = FALSE
      )
    }

    if (!dir.exists(outdir)) {
      created <- dir.create(
        outdir,
        recursive = TRUE,
        showWarnings = FALSE
      )

      if (!created && !dir.exists(outdir)) {
        stop(
          "Could not create output directory: ",
          outdir,
          call. = FALSE
        )
      }
    }

    out_path <- file.path(
      outdir,
      paste0(
        "diversity_",
        boot$label_safe,
        "_summary.tsv"
      )
    )

    readr::write_tsv(
      summary_tbl,
      out_path
    )
  }

  if (verbose) {

    cat(
      "\nBootstrap diversity summary:\n",
      "  Bootstrap replicates: ",
      nrow(summary_tbl),
      "\n",
      "  Taxid source:         ",
      boot$composite_taxids,
      "\n",
      sep = ""
    )

    if (!is.null(out_path)) {
      cat(
        "  Summary written to:  ",
        normalizePath(
          out_path,
          winslash = "/",
          mustWork = FALSE
        ),
        "\n",
        sep = ""
      )
    }

    cat("\n")
  }

  invisible(
    list(
      label = boot$label,
      label_safe = boot$label_safe,
      summary = summary_tbl,
      path = out_path
    )
  )
}


# Internal plotting helper ------------------------------------------------

.bootstrap_stats_long <- function(
    stats,
    metrics
) {

  if (
    is.list(stats) &&
    !is.null(stats$summary) &&
    is.data.frame(stats$summary)
  ) {
    summary_tbl <- stats$summary

  } else if (is.data.frame(stats)) {
    summary_tbl <- stats

  } else {
    stop(
      "stats must be the result returned by bootstrap_stats() ",
      "or its summary table.",
      call. = FALSE
    )
  }

  keep <- intersect(
    metrics,
    names(summary_tbl)
  )

  if (length(keep) == 0L) {
    stop(
      "No requested metrics found in the summary table.",
      call. = FALSE
    )
  }

  summary_tbl |>
    dplyr::select(
      sample_id,
      replicate,
      dplyr::all_of(keep)
    ) |>
    tidyr::pivot_longer(
      cols = dplyr::all_of(keep),
      names_to = "metric",
      values_to = "value"
    )
}


#' Plot bootstrap diversity statistics
#'
#' Plots diversity statistics calculated by [bootstrap_stats()].
#'
#' @param stats A result returned by [bootstrap_stats()] or its `summary`
#'   table.
#' @param metrics Character vector of metrics to plot.
#' @param type Plot type. `"distribution"` produces histograms,
#'   `"replicate"` plots values by bootstrap replicate, and `"boxplot"`
#'   summarizes the distribution of each metric.
#' @param facet_scales Scales passed to `ggplot2::facet_wrap()`.
#'
#' @return A ggplot object.
#'
#' @examples
#' \dontrun{
#' stats <- bootstrap_stats(boot)
#'
#' plot_bootstrap_stats(stats)
#'
#' plot_bootstrap_stats(
#'   stats,
#'   type = "replicate"
#' )
#' }
#'
#' @export
plot_bootstrap_stats <- function(
    stats,
    metrics = c(
      "n_unique_taxa",
      "shannon",
      "gini_simpson",
      "inverse_simpson",
      "pielou_evenness"
    ),
    type = c(
      "distribution",
      "replicate",
      "boxplot"
    ),
    facet_scales = "free_y"
) {

  type <- match.arg(type)

  long <- .bootstrap_stats_long(
    stats,
    metrics
  )

  if (type == "distribution") {

    return(
      ggplot2::ggplot(
        long,
        ggplot2::aes(x = value)
      ) +
        ggplot2::geom_histogram(
          bins = 30
        ) +
        ggplot2::facet_wrap(
          ~ metric,
          scales = facet_scales
        ) +
        ggplot2::labs(
          x = NULL,
          y = "Bootstrap replicates"
        )
    )
  }


  if (type == "replicate") {

    return(
      ggplot2::ggplot(
        long,
        ggplot2::aes(
          x = replicate,
          y = value
        )
      ) +
        ggplot2::geom_col() +
        ggplot2::facet_wrap(
          ~ metric,
          scales = facet_scales
        ) +
        ggplot2::labs(
          x = "Bootstrap replicate",
          y = NULL
        )
    )
  }


  ggplot2::ggplot(
    long,
    ggplot2::aes(
      x = metric,
      y = value
    )
  ) +
    ggplot2::geom_boxplot(
      outlier.alpha = 0.4
    ) +
    ggplot2::facet_wrap(
      ~ metric,
      scales = facet_scales
    ) +
    ggplot2::labs(
      x = NULL,
      y = NULL
    ) +
    ggplot2::theme(
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank()
    )
}
